<?php

namespace Database\Seeders;

use App\Models\Produto;
use Illuminate\Database\Seeder;

class ProdutoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $produtos = [
            [
                'tipo_produto_id' => 2,
                'fabricante_id' => 1,
                'nome_produto' => 'Desktop Gamer Extreme',
                'sku' => 'SKU123',
                'descricao' => 'Potente desktop para jogos de última geração',
                'preco' => 1999.99,
                'vendedor' => 'Loja de Tecnologia',
                'quantidade' => 50,
                'data_criacao' => '2023-12-11 18:00:00',
                'modelo' => 'ModeloXYZ',
            ],
            [
                'tipo_produto_id' => 2,
                'fabricante_id' => 2,
                'nome_produto' => 'Desktop para Uso Doméstico',
                'sku' => 'SKU456',
                'descricao' => 'Desktop ideal para uso diário em casa',
                'preco' => 799.99,
                'vendedor' => 'Loja de Eletrônicos',
                'quantidade' => 30,
                'data_criacao' => '2023-12-11 18:05:00',
                'modelo' => 'ModeloABC',
            ],
            [
                'tipo_produto_id' => 1,
                'fabricante_id' => 3,
                'nome_produto' => 'Notebook Profissional Lenovo',
                'sku' => 'SKU789',
                'descricao' => 'Notebook potente para uso profissional',
                'preco' => 1499.99,
                'vendedor' => 'Loja de Informática',
                'quantidade' => 20,
                'data_criacao' => '2023-12-11 18:10:00',
                'modelo' => 'Modelo123',
            ],
            [
                'tipo_produto_id' => 3,
                'fabricante_id' => 4,
                'nome_produto' => 'Desktop Design Gráfico Dell',
                'sku' => 'SKU101',
                'descricao' => 'Desktop otimizado para design gráfico',
                'preco' => 1699.99,
                'vendedor' => 'Loja de Computadores',
                'quantidade' => 25,
                'data_criacao' => '2023-12-11 18:15:00',
                'modelo' => 'Modelo456',
            ],
            [
                'tipo_produto_id' => 4,
                'fabricante_id' => 5,
                'nome_produto' => 'Desktop Econômico Acer',
                'sku' => 'SKU202',
                'descricao' => 'Desktop acessível para uso diário',
                'preco' => 599.99,
                'vendedor' => 'Loja de Tecnologia',
                'quantidade' => 40,
                'data_criacao' => '2023-12-11 18:20:00',
                'modelo' => 'Modelo789',
            ],
            [
                'tipo_produto_id' => 6,
                'fabricante_id' => 6,
                'nome_produto' => 'Notebook Conversível Asus',
                'sku' => 'SKU303',
                'descricao' => 'Notebook versátil com tela conversível',
                'preco' => 1299.99,
                'vendedor' => 'Loja de Eletrônicos',
                'quantidade' => 15,
                'data_criacao' => '2023-12-11 18:25:00',
                'modelo' => 'Modelo101',
            ],
            [
                'tipo_produto_id' => 7,
                'fabricante_id' => 7,
                'nome_produto' => 'Impressora Laser Monocromática Toshiba',
                'sku' => 'SKU404',
                'descricao' => 'Impressora monocromática de alta qualidade',
                'preco' => 299.99,
                'vendedor' => 'Loja de Impressoras',
                'quantidade' => 10,
                'data_criacao' => '2023-12-11 18:30:00',
                'modelo' => 'Modelo202',
            ],
            [
                'tipo_produto_id' => 9,
                'fabricante_id' => 8,
                'nome_produto' => 'Impressora Multifuncional Wi-Fi Microsoft',
                'sku' => 'SKU505',
                'descricao' => 'Impressora multifuncional com conectividade sem fio',
                'preco' => 349.99,
                'vendedor' => 'Loja de Tecnologia',
                'quantidade' => 18,
                'data_criacao' => '2023-12-11 18:35:00',
                'modelo' => 'Modelo303',
            ],
            [
                'tipo_produto_id' => 13,
                'fabricante_id' => 9,
                'nome_produto' => 'Monitor LED Full HD Fujitsu',
                'sku' => 'SKU606',
                'descricao' => 'Monitor de alta definição para experiência visual excepcional',
                'preco' => 249.99,
                'vendedor' => 'Loja de Monitores',
                'quantidade' => 22,
                'data_criacao' => '2023-12-11 18:40:00',
                'modelo' => 'Modelo404',
            ],
            [
                'tipo_produto_id' => 14,
                'fabricante_id' => 10,
                'nome_produto' => 'Monitor Ultrawide Curvo Samsung',
                'sku' => 'SKU707',
                'descricao' => 'Monitor ultrawide com design curvo para imersão total',
                'preco' => 799.99,
                'vendedor' => 'Loja de Tecnologia',
                'quantidade' => 12,
                'data_criacao' => '2023-12-11 18:45:00',
                'modelo' => 'Modelo505',
            ],
            [
                'tipo_produto_id' => 5,
                'fabricante_id' => 11,
                'nome_produto' => 'Notebook Leve Sony',
                'sku' => 'SKU808',
                'descricao' => 'Notebook leve e portátil da Sony',
                'preco' => 1199.99,
                'vendedor' => 'Loja de Eletrônicos',
                'quantidade' => 25,
                'data_criacao' => '2023-12-11 19:00:00',
                'modelo' => 'Modelo606',
            ],
            [
                'tipo_produto_id' => 6,
                'fabricante_id' => 12,
                'nome_produto' => 'Notebook Conversível LG',
                'sku' => 'SKU909',
                'descricao' => 'Notebook conversível da LG com design inovador',
                'preco' => 1399.99,
                'vendedor' => 'Loja de Tecnologia',
                'quantidade' => 20,
                'data_criacao' => '2023-12-11 19:05:00',
                'modelo' => 'Modelo707',
            ],
            [
                'tipo_produto_id' => 8,
                'fabricante_id' => 13,
                'nome_produto' => 'Impressora Jato de Tinta LG',
                'sku' => 'SKU1010',
                'descricao' => 'Impressora jato de tinta colorida da LG',
                'preco' => 179.99,
                'vendedor' => 'Loja de Impressoras',
                'quantidade' => 15,
                'data_criacao' => '2023-12-11 19:10:00',
                'modelo' => 'Modelo808',
            ],
            [
                'tipo_produto_id' => 10,
                'fabricante_id' => 14,
                'nome_produto' => 'Impressora de Etiquetas Gigabyte',
                'sku' => 'SKU1111',
                'descricao' => 'Impressora de etiquetas para negócios da Gigabyte',
                'preco' => 249.99,
                'vendedor' => 'Loja de Tecnologia',
                'quantidade' => 12,
                'data_criacao' => '2023-12-11 19:15:00',
                'modelo' => 'Modelo909',
            ],
            [
                'tipo_produto_id' => 11,
                'fabricante_id' => 15,
                'nome_produto' => 'Monitor 4K Xiaomi',
                'sku' => 'SKU1212',
                'descricao' => 'Monitor 4K para edição de vídeo da Xiaomi',
                'preco' => 599.99,
                'vendedor' => 'Loja de Monitores',
                'quantidade' => 18,
                'data_criacao' => '2023-12-11 19:20:00',
                'modelo' => 'Modelo1010',
            ],
            [
                'tipo_produto_id' => 12,
                'fabricante_id' => 1,
                'nome_produto' => 'Monitor Curvo Lenovo',
                'sku' => 'SKU1313',
                'descricao' => 'Monitor curvo para jogos da Lenovo',
                'preco' => 899.99,
                'vendedor' => 'Loja de Tecnologia',
                'quantidade' => 22,
                'data_criacao' => '2023-12-11 19:25:00',
                'modelo' => 'Modelo1111',
            ],
            [
                'tipo_produto_id' => 13,
                'fabricante_id' => 2,
                'nome_produto' => 'Monitor Ultrawide HP Inc.',
                'sku' => 'SKU1414',
                'descricao' => 'Monitor ultrawide para produtividade da HP Inc.',
                'preco' => 749.99,
                'vendedor' => 'Loja de Monitores',
                'quantidade' => 15,
                'data_criacao' => '2023-12-11 19:30:00',
                'modelo' => 'Modelo1212',
            ],
            [
                'tipo_produto_id' => 14,
                'fabricante_id' => 3,
                'nome_produto' => 'Monitor Gaming Dell',
                'sku' => 'SKU1515',
                'descricao' => 'Monitor curvo para jogos da Dell',
                'preco' => 1099.99,
                'vendedor' => 'Loja de Tecnologia',
                'quantidade' => 20,
                'data_criacao' => '2023-12-11 19:35:00',
                'modelo' => 'Modelo1313',
            ],
            [
                'tipo_produto_id' => 1,
                'fabricante_id' => 4,
                'nome_produto' => 'Notebook Apple Pro',
                'sku' => 'SKU1616',
                'descricao' => 'Notebook profissional da Apple',
                'preco' => 2399.99,
                'vendedor' => 'Loja de Eletrônicos',
                'quantidade' => 10,
                'data_criacao' => '2023-12-11 19:40:00',
                'modelo' => 'Modelo1414',
            ],
            [
                'tipo_produto_id' => 3,
                'fabricante_id' => 5,
                'nome_produto' => 'Desktop para Design Gráfico Acer',
                'sku' => 'SKU1717',
                'descricao' => 'Desktop otimizado para design gráfico da Acer',
                'preco' => 1599.99,
                'vendedor' => 'Loja de Computadores',
                'quantidade' => 18,
                'data_criacao' => '2023-12-11 19:45:00',
                'modelo' => 'Modelo1515',
            ],
        ];

        foreach ($produtos as $produto) {
            Produto::create($produto);
        }
    }
}
